//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string nationid { get; set; }
        public string sex { get; set; }
        public Nullable<int> phnum { get; set; }
        public string bloudtype { get; set; }
    }
}
